/*
  Module: Data
  Purpose: Mock/demo data for Redis table
*/
export const redisData = {
  lastUpdated: "16:50:01",
  redis: [
    {
      host: "equify-gcp-vm6",
      timestamp: "2025-08-07T16:30:01",
      componentType: "Redis",
      name: "Redis1",
      status: "Active",
      cpu: 0.2,
      memory: 0,
      exceededThreshold: false,
    },
    {
      host: "equify-gcp-vm7",
      timestamp: "2025-08-07T16:30:01",
      componentType: "Redis",
      name: "Redis2",
      status: "Inactive",
      cpu: 25.4,
      memory: 63.3,
      exceededThreshold: false,
    },
    {
      host: "aws-redis-01",
      timestamp: "2025-08-07T16:30:01",
      componentType: "Redis",
      name: "RedisProdA",
      status: "Degraded",
      cpu: 78.9,
      memory: 81.2,
      exceededThreshold: true,
    },
    {
      host: "aws-redis-02",
      timestamp: "2025-08-07T16:30:01",
      componentType: "Redis",
      name: "RedisProdB",
      status: "Active",
      cpu: 5.3,
      memory: 12.1,
      exceededThreshold: false,
    },
    {
      host: "azure-redis-01",
      timestamp: "2025-08-07T16:30:01",
      componentType: "Redis",
      name: "RedisCacheX",
      status: "Maintenance",
      cpu: 0.0,
      memory: 0.5,
      exceededThreshold: false,
    },
    {
      host: "local-redis",
      timestamp: "2025-08-07T16:30:01",
      componentType: "Redis",
      name: "DevRedis",
      status: "Active",
      cpu: 1.2,
      memory: 3.4,
      exceededThreshold: false,
    },
    {
      host: "gcp-redis-03",
      timestamp: "2025-08-07T16:30:01",
      componentType: "Redis",
      name: "RedisEU",
      status: "Inactive",
      cpu: 55.0,
      memory: 22.2,
      exceededThreshold: false,
    },
    {
      host: "gcp-redis-04",
      timestamp: "2025-08-07T16:30:01",
      componentType: "Redis",
      name: "RedisAPAC",
      status: "Active",
      cpu: 42.0,
      memory: 68.0,
      exceededThreshold: true,
    },
  ],
};
